version: "2"

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - discovery.type=single-node
  cerebro:
    image: dylanmei/cerebro
    ports:
    - 9000:9000
    command:
    - bin/cerebro
    - -Dhosts.0.host=http://elasticsearch:9200